In [1]:
# Example 01: NumPy - Basic Indexing and Slicing
import numpy as np

# Creating an array
array = np.array([10, 20, 30, 40, 50])

# Accessing elements by index
first_element = array[0]
last_element = array[-1]

# Slicing the array
slice_array = array[1:4]

print('First Element:', first_element)
print('Last Element:', last_element)
print('Sliced Array:', slice_array)


First Element: 10
Last Element: 50
Sliced Array: [20 30 40]


In [2]:

# Example 02: NumPy - Array Creation Basics
import numpy as np

# Creating arrays with different functions
array_zeros = np.zeros((3, 3))
array_ones = np.ones((2, 2))
array_full = np.full((2, 2), 7)
array_range = np.arange(10)

print('Array of Zeros:\n', array_zeros)
print('Array of Ones:\n', array_ones)
print('Array with All Elements as 7:\n', array_full)
print('Array with Range of Numbers:', array_range)


Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of Ones:
 [[1. 1.]
 [1. 1.]]
Array with All Elements as 7:
 [[7 7]
 [7 7]]
Array with Range of Numbers: [0 1 2 3 4 5 6 7 8 9]


In [3]:

# Example 03: NumPy - Basic Arithmetic Operations
import numpy as np

# Creating arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Arithmetic operations
added = np.add(array1, array2)
subtracted = np.subtract(array1, array2)
multiplied = np.multiply(array1, array2)
divided = np.divide(array1, array2)

print('Added:', added)
print('Subtracted:', subtracted)
print('Multiplied:', multiplied)
print('Divided:', divided)


Added: [5 7 9]
Subtracted: [-3 -3 -3]
Multiplied: [ 4 10 18]
Divided: [0.25 0.4  0.5 ]


In [4]:

# Example 04: NumPy - 2D Array Indexing
import numpy as np

# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing individual elements
element = array_2d[1, 2]  # Accessing element at row 1, column 2

# Slicing rows and columns
row_slice = array_2d[0, :]  # First row
column_slice = array_2d[:, 1]  # Second column


print('Element at (1,2):', element)
print('First Row:', row_slice)
print('Second Column:', column_slice)


Element at (1,2): 6
First Row: [1 2 3]
Second Column: [2 5 8]


In [5]:
# Example 05: NumPy - Boolean Indexing
import numpy as np

# Creating an array
array = np.array([10, 15, 20, 25, 30])

# Boolean indexing
greater_than_20 = array[array > 20]

print('Elements Greater Than 20:', greater_than_20)


Elements Greater Than 20: [25 30]


In [6]:

# Example 06: NumPy - Power and Square Root
import numpy as np

# Creating an array
array = np.array([1, 4, 9, 16])

# Power and square root
squared = np.power(array, 2)
sqrt = np.sqrt(array)

print('Squared Array:', squared)
print('Square Root of Array:', sqrt)


Squared Array: [  1  16  81 256]
Square Root of Array: [1. 2. 3. 4.]


In [7]:
# Example 07: NumPy - Exponential and Logarithmic Functions
import numpy as np

# Creating an array
array = np.array([1, 2, 3])

# Exponential and logarithmic functions
exp_array = np.exp(array)
log_array = np.log(array)

print('Exponential of Array:', exp_array)
print('Logarithm of Array:', log_array)


Exponential of Array: [ 2.71828183  7.3890561  20.08553692]
Logarithm of Array: [0.         0.69314718 1.09861229]


In [8]:
# Example 08: NumPy - Fancy Indexing
import numpy as np

# Creating an array
array = np.array([10, 20, 30, 40, 50])

# Selecting specific indices
selected_elements = array[[1, 3, 4]]

print('Selected Elements:', selected_elements)


Selected Elements: [20 40 50]


In [9]:

# Example 09: NumPy - Slicing with Step
import numpy as np

# Creating an array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Slicing with a step
step_slice = array[::2]  # Every second element

print('Sliced Array with Step 2:', step_slice)


Sliced Array with Step 2: [1 3 5 7 9]


In [10]:
# Example 10: NumPy - Trigonometric Functions
import numpy as np

# Creating an array
angles = np.array([0, np.pi/2, np.pi])

# Trigonometric functions
sin_array = np.sin(angles)
cos_array = np.cos(angles)
tan_array = np.tan(angles)

print('Sine of Angles:', sin_array)
print('Cosine of Angles:', cos_array)
print('Tangent of Angles:', tan_array)


Sine of Angles: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine of Angles: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Tangent of Angles: [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [11]:
# Example 11: NumPy - 3D Array Indexing
import numpy as np

# Creating a 3D array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Accessing elements in a 3D array
element = array_3d[1, 0, 1]  # Accessing the element at [1, 0, 1]

# Slicing in 3D
slice_3d = array_3d[:, 0, :]

print('Element at (1,0,1):', element)
print('Sliced 3D Array:\n', slice_3d)


Element at (1,0,1): 6
Sliced 3D Array:
 [[1 2]
 [5 6]]


In [1]:
# Example 12: NumPy - Indexing with Arrays
import numpy as np

# Creating a 2D array
array_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# Using arrays for indexing
rows = np.array([0, 1, 2])
cols = np.array([2, 1, 0])
indexed_elements = array_2d[rows, cols]

print('Indexed Elements:', indexed_elements)


Indexed Elements: [30 50 70]


In [2]:
# Example 13: NumPy - Reshaping Arrays
import numpy as np

# Creating an array
array = np.array([1, 2, 3, 4, 5, 6])

# Reshaping to different dimensions
reshaped_array = array.reshape((2, 3))

print('Original Array:', array)
print('Reshaped Array:\n', reshaped_array)


Original Array: [1 2 3 4 5 6]
Reshaped Array:
 [[1 2 3]
 [4 5 6]]


In [3]:
# Example 14: NumPy - Conditional Indexing
import numpy as np

# Creating an array
array = np.array([1, 2, 3, 4, 5, 6])

# Setting elements that satisfy a condition
array[array % 2 == 0] = -1  # Set even numbers to -1

print('Array after Conditional Indexing:', array)


Array after Conditional Indexing: [ 1 -1  3 -1  5 -1]


In [4]:
# Example 15: NumPy - Transposing Arrays
import numpy as np

# Creating a 2D array
array = np.array([[1, 2], [3, 4]])

# Transposing the array
transposed_array = np.transpose(array)

print('Original Array:\n', array)
print('Transposed Array:\n', transposed_array)


Original Array:
 [[1 2]
 [3 4]]
Transposed Array:
 [[1 3]
 [2 4]]


In [5]:

# Example 16: NumPy - Broadcasting
import numpy as np

# Creating an array
array = np.array([1, 2, 3])

# Broadcasting: Adding a scalar to an array
result = array + 10

print('Original Array:', array)
print('Array after Broadcasting:', result)


Original Array: [1 2 3]
Array after Broadcasting: [11 12 13]


In [6]:
# Example 17: NumPy - Multi-dimensional Slicing
import numpy as np

# Creating a 2D array
array_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Multi-dimensional slicing
sub_array = array_2d[1:, 1:3]

print('Sub Array (Slicing Rows and Columns):\n', sub_array)


Sub Array (Slicing Rows and Columns):
 [[ 6  7]
 [10 11]]


In [7]:
# Example 18: NumPy - Modifying Array Values using Indexing
import numpy as np

# Creating an array
array = np.array([10, 20, 30, 40, 50])

# Modifying values at specific indices
array[[1, 3]] = [100, 200]

print('Modified Array:', array)


Modified Array: [ 10 100  30 200  50]


In [8]:
# Example 19: NumPy - Sorting Arrays
import numpy as np

# Creating an array
array = np.array([3, 1, 2, 5, 4])

# Sorting the array
sorted_array = np.sort(array)

print('Original Array:', array)
print('Sorted Array:', sorted_array)


Original Array: [3 1 2 5 4]
Sorted Array: [1 2 3 4 5]


In [9]:
# Example 20: NumPy - Indexing with Negative Indices
import numpy as np

# Creating an array
array = np.array([10, 20, 30, 40, 50])

# Accessing elements from the end using negative indices
last_element = array[-1]
second_last_element = array[-2]

print('Last Element:', last_element)
print('Second Last Element:', second_last_element)


Last Element: 50
Second Last Element: 40


In [10]:
# Example 21: NumPy - Random Array Generation
import numpy as np

# Generating random arrays
random_array = np.random.rand(3, 3)  # Random values in a 3x3 array
normal_array = np.random.randn(3, 3)  # Random values with a normal distribution

print('Random Array:\n', random_array)
print('Normal Distribution Array:\n', normal_array)


Random Array:
 [[0.63303393 0.58000018 0.46044236]
 [0.11416505 0.46946587 0.86297994]
 [0.35085239 0.08040021 0.23255809]]
Normal Distribution Array:
 [[ 1.20515242 -0.00233989 -1.11155756]
 [-0.40131099  1.30652824  0.64611104]
 [-0.10906777  0.31987741 -0.96115755]]


In [11]:
# Example 22: NumPy - Boolean Indexing
import numpy as np

# Creating an array
array = np.array([1, 2, 3, 4, 5, 6])

# Boolean indexing
even_numbers = array[array % 2 == 0]

print('Original Array:', array)
print('Even Numbers:', even_numbers)


Original Array: [1 2 3 4 5 6]
Even Numbers: [2 4 6]


In [12]:

# Example 23: NumPy - Combining Boolean and Fancy Indexing
import numpy as np

# Creating an array
array = np.array([10, 15, 20, 25, 30])

# Boolean condition combined with specific indices
result = array[(array > 10) & (array < 30)][[0, 2]]

print('Combined Boolean and Fancy Indexing Result:', result)


Combined Boolean and Fancy Indexing Result: [15 25]


In [13]:

# Example 24: NumPy - Indexing Multi-dimensional Arrays with Slices
import numpy as np

# Creating a 3x4 array
array_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Selecting specific rows and columns using slices
selected_slice = array_2d[1:, :2]

print('Selected Slice:\n', selected_slice)


Selected Slice:
 [[ 5  6]
 [ 9 10]]


In [14]:
# Example 25: NumPy - Statistical Functions
import numpy as np

# Creating an array
array = np.array([1, 2, 3, 4, 5])

# Calculating statistical values
mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
variance = np.var(array)

print('Mean:', mean)
print('Median:', median)
print('Standard Deviation:', std_dev)
print('Variance:', variance)


Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0


In [15]:
# Example 26: NumPy - Using Ellipsis (...) in Indexing
import numpy as np

# Creating a 3D array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

# Using ellipsis to select all elements along specific axes
result = array_3d[..., 1]  # Selecting the second column in each 2D slice

print('Result using Ellipsis (...):\n', result)


Result using Ellipsis (...):
 [[ 2  4]
 [ 6  8]
 [10 12]]


In [16]:
# Example 27: NumPy - Unique Elements and Counting
import numpy as np

# Creating an array with duplicate values
array = np.array([1, 2, 2, 3, 4, 4, 4, 5])

# Finding unique elements and their counts
unique_elements, counts = np.unique(array, return_counts=True)

print('Unique Elements:', unique_elements)
print('Counts of Unique Elements:', counts)


Unique Elements: [1 2 3 4 5]
Counts of Unique Elements: [1 2 1 3 1]


In [17]:
# Example 28: NumPy - Concatenation of Arrays
import numpy as np

# Creating arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Concatenating arrays
concatenated_array = np.concatenate((array1, array2))

print('Concatenated Array:', concatenated_array)


Concatenated Array: [1 2 3 4 5 6]


In [18]:
# Example 29: NumPy - Masked Indexing
import numpy as np

# Creating an array
array = np.array([1, -2, 3, -4, 5])

# Creating a mask for positive values
mask = array > 0

# Applying mask to get only positive values
positive_values = array[mask]

print('Positive Values:', positive_values)


Positive Values: [1 3 5]


In [19]:

# Example 30: NumPy - Extracting Diagonal Elements
import numpy as np

# Creating a square matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Extracting the main diagonal
diagonal_elements = np.diag(matrix)

print('Diagonal Elements:', diagonal_elements)


Diagonal Elements: [1 5 9]


In [20]:
# Example 31: NumPy - Splitting Arrays
import numpy as np

# Creating an array
array = np.array([1, 2, 3, 4, 5, 6])

# Splitting the array into three parts
split_arrays = np.array_split(array, 3)

print('Split Arrays:', split_arrays)


Split Arrays: [array([1, 2]), array([3, 4]), array([5, 6])]


In [21]:
# Example 32: NumPy - Indexing with np.where()
import numpy as np

# Creating an array
array = np.array([10, 20, 30, 40, 50])

# Using np.where to find indices where elements are greater than 25
indices = np.where(array > 25)

print('Indices where elements > 25:', indices)
print('Values where elements > 25:', array[indices])


Indices where elements > 25: (array([2, 3, 4], dtype=int64),)
Values where elements > 25: [30 40 50]


In [22]:
# Example 33: NumPy - Linear Space Array
import numpy as np

# Generating a linear space array with evenly spaced values
linear_space = np.linspace(0, 10, 5)

print('Linear Space Array:', linear_space)


Linear Space Array: [ 0.   2.5  5.   7.5 10. ]


In [23]:
# Example 34: NumPy - Advanced Slicing with Step in 2D Array
import numpy as np

# Creating a 2D array
array_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Slicing every second element in rows and columns
result = array_2d[::2, ::2]

print('Advanced Sliced Array with Step:\n', result)


Advanced Sliced Array with Step:
 [[ 1  3]
 [ 9 11]]


In [24]:
# Example 35: NumPy - Meshgrid Creation
import numpy as np

# Creating 1D arrays
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Creating a meshgrid
X, Y = np.meshgrid(x, y)

print('Meshgrid X:\n', X)
print('Meshgrid Y:\n', Y)


Meshgrid X:
 [[1 2 3]
 [1 2 3]
 [1 2 3]]
Meshgrid Y:
 [[4 4 4]
 [5 5 5]
 [6 6 6]]


In [25]:
# Example 36: NumPy - Clipping Array Values
import numpy as np

# Creating an array
array = np.array([1, 2, 3, 4, 5])

# Clipping values to be between 2 and 4
clipped_array = np.clip(array, 2, 4)

print('Original Array:', array)
print('Clipped Array:', clipped_array)


Original Array: [1 2 3 4 5]
Clipped Array: [2 2 3 4 4]


In [26]:
# Example 37: NumPy - Setting Values Using Indexing
import numpy as np

# Creating an array
array = np.array([1, 2, 3, 4, 5])

# Setting specific values using indexing
array[[1, 3]] = [100, 200]

print('Array after Setting Values:', array)


Array after Setting Values: [  1 100   3 200   5]


In [27]:
# Example 38: NumPy - Cumulative Sum and Product
import numpy as np

# Creating an array
array = np.array([1, 2, 3, 4])

# Calculating cumulative sum and product
cumulative_sum = np.cumsum(array)
cumulative_product = np.cumprod(array)

print('Cumulative Sum:', cumulative_sum)
print('Cumulative Product:', cumulative_product)


Cumulative Sum: [ 1  3  6 10]
Cumulative Product: [ 1  2  6 24]


In [28]:
# Example 39: NumPy - Extracting Upper Triangle of a Matrix
import numpy as np

# Creating a square matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Extracting the upper triangle (above the main diagonal)
upper_triangle = np.triu(matrix)

print('Upper Triangle of the Matrix:\n', upper_triangle)


Upper Triangle of the Matrix:
 [[1 2 3]
 [0 5 6]
 [0 0 9]]


In [1]:
# Example 40: NumPy - Reverse Array using Indexing
import numpy as np

# Creating an array
array = np.array([1, 2, 3, 4, 5])

# Reversing the array using slicing
reversed_array = array[::-1]

print('Reversed Array:', reversed_array)


Reversed Array: [5 4 3 2 1]


In [29]:

# Example 41: NumPy - Extract Lower Triangle of a Matrix
import numpy as np

# Creating a square matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Extracting the lower triangle (below the main diagonal)
lower_triangle = np.tril(matrix)

print('Lower Triangle of the Matrix:\n', lower_triangle)


Lower Triangle of the Matrix:
 [[1 0 0]
 [4 5 0]
 [7 8 9]]


In [30]:
# Example 42: NumPy - Multi-dimensional Array Indexing with Mixed Types
import numpy as np

# Creating a 3D array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

# Mixing slicing with direct indexing
mixed_index = array_3d[1:, 0, 1]

print('Mixed Type Indexing Result:', mixed_index)


Mixed Type Indexing Result: [ 6 10]


In [31]:
# Example 43: NumPy - Indexing with np.take
import numpy as np

# Creating an array
array = np.array([10, 20, 30, 40, 50])

# Using np.take to select elements at specific indices
indices = [0, 2, 4]
result = np.take(array, indices)

print('Selected Elements using np.take:', result)


Selected Elements using np.take: [10 30 50]


In [32]:

# Example 44: NumPy - Masked Indexing with np.ma.masked_where
import numpy as np

# Creating an array
array = np.array([1, -2, 3, -4, 5])

# Masking elements where values are negative
masked_array = np.ma.masked_where(array < 0, array)

print('Masked Array with Negative Values Hidden:', masked_array)


Masked Array with Negative Values Hidden: [1 -- 3 -- 5]


In [33]:
# Example 45: NumPy - Flattening a Multi-dimensional Array
import numpy as np

# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Flattening the array
flattened_array = array_2d.flatten()

print('Flattened Array:', flattened_array)


Flattened Array: [1 2 3 4 5 6]


In [34]:
# Example 46: NumPy - Advanced Indexing with Meshgrid
import numpy as np

# Creating 1D arrays
x = np.array([1, 2, 3])
y = np.array([4, 5])

# Creating meshgrid for advanced indexing
X, Y = np.meshgrid(x, y)
indices = np.vstack([X.ravel(), Y.ravel()])

print('Indices for Meshgrid Advanced Indexing:\n', indices)


Indices for Meshgrid Advanced Indexing:
 [[1 2 3 1 2 3]
 [4 4 4 5 5 5]]


In [35]:
# Example 47: NumPy - Conditional Replacement with np.where
import numpy as np

# Creating an array
array = np.array([10, 15, 20, 25, 30])

# Replacing values based on condition
result = np.where(array > 20, 0, array)

print('Array with Values Greater Than 20 Replaced with 0:', result)


Array with Values Greater Than 20 Replaced with 0: [10 15 20  0  0]


In [3]:
# Example 48: NumPy - Using np.choose for Multiple Conditions
import numpy as np

# Creating arrays for conditions
array = np.array([0, 1, 2, 3])
choices = [array*2, array+10, array**2]

# Using np.choose to apply different conditions
result = np.choose( [1,1,0,1], choices)

print('Result using np.choose:', result)
print(choices)


Result using np.choose: [10 11  4 13]
[array([0, 2, 4, 6]), array([10, 11, 12, 13]), array([0, 1, 4, 9])]


In [4]:
# Example 49: NumPy - Using np.choose for Multiple Conditions
import numpy as np

# Creating arrays for conditions
array = np.array([0, 1, 2, 3])
choices = [array*2, array+10, array**2]

# Using np.choose to apply different conditions
result = np.choose([1,1,0,1], choices)

print('Result using np.choose:', result)


Result using np.choose: [10 11  4 13]


In [6]:

# Example 50: NumPy - Combining Multiple Indexing Techniques
import numpy as np

# Creating a 2D array
array_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# Combining boolean, fancy, and slice indexing
result = array_2d[array_2d > 30][: 2]

print('Combined Indexing Result:', result)


Combined Indexing Result: [40 50]
